load("@rules_python//python:python.bzl", "py_library")

py_library(
    name = "deps",
    visibility = ["//visibility:public"],
    deps = [
        "@python_deps_cachetools//:pkg",
        "@python_deps_certifi//:pkg",
        "@python_deps_charset_normalizer//:pkg",
        "@python_deps_elastic_transport//:pkg",
        "@python_deps_elasticsearch//:pkg",
        "@python_deps_google_api_core//:pkg",
        "@python_deps_google_auth//:pkg",
        "@python_deps_google_cloud_core//:pkg",
        "@python_deps_google_cloud_storage//:pkg",
        "@python_deps_google_crc32c//:pkg",
        "@python_deps_google_resumable_media//:pkg",
        "@python_deps_googleapis_common_protos//:pkg",
        "@python_deps_idna//:pkg",
        "@python_deps_protobuf//:pkg",
        "@python_deps_pyasn1//:pkg",
        "@python_deps_pyasn1_modules//:pkg",
        "@python_deps_requests//:pkg",
        "@python_deps_rsa//:pkg",
        "@python_deps_six//:pkg",
        "@python_deps_urllib3//:pkg",
    ],
)
