load("@rules_python//python:python.bzl", "py_library")
load("@python_deps//:requirements.bzl", "requirement")

py_library(
    name = "deps",
    visibility = ["//visibility:public"],
    deps = [
        requirement("cachetools"),
        requirement("certifi"),
        requirement("charset_normalizer"),
        requirement("elastic_transport"),
        requirement("elasticsearch"),
        requirement("google_api_core"),
        requirement("google_auth"),
        requirement("google_cloud_core"),
        requirement("google_cloud_storage"),
        requirement("google_crc32c"),
        requirement("google_resumable_media"),
        requirement("googleapis_common_protos"),
        requirement("idna"),
        requirement("protobuf"),
        requirement("pyasn1"),
        requirement("pyasn1_modules"),
        requirement("requests"),
        requirement("rsa"),
        requirement("setuptools"),
        requirement("six"),
        requirement("urllib3"),
    ],
)
